// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIA4G0vhDbQjcxw4_ZoVLmWiqbSbkeWWo',
    appId: '1:971423117270:web:4e9a92fa0bc4aa6267be77',
    messagingSenderId: '971423117270',
    projectId: 'ta-mopro-92a89',
    authDomain: 'ta-mopro-92a89.firebaseapp.com',
    storageBucket: 'ta-mopro-92a89.firebasestorage.app',
    measurementId: 'G-TWP9HYXMDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgy4A1jauJ01_eD7GpCKBjojySfFJx1T0',
    appId: '1:971423117270:android:f5a4da6d1f282ba767be77',
    messagingSenderId: '971423117270',
    projectId: 'ta-mopro-92a89',
    storageBucket: 'ta-mopro-92a89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDonC2TVekRgNF4GX1yswqyMRpBRZHCKio',
    appId: '1:971423117270:ios:67d1a70a38080ffb67be77',
    messagingSenderId: '971423117270',
    projectId: 'ta-mopro-92a89',
    storageBucket: 'ta-mopro-92a89.firebasestorage.app',
    iosBundleId: 'com.example.prelovedly',
  );
}
